In [1]:
# Importing dictionaries 
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

## Store xlsx into Data Frame

In [2]:
# Reading the excel file 

excel_file = 'Resources/Texas 2017 Quotes.xlsx'

texas_df = pd.read_excel(excel_file)
texas_df.head(25)

,BID_CODE,bid_no_calc,BID_YEAR,budgetary,C_city,C_country,C_cust_name,C_state,C_zip,Contact_seq,...,docs::filename,docs::position,docs::seq,Quote_Line::calc_discount,Rep code_owner_assigned::REP_ORG_CONTACT,RepCode_inst::REP_ORG_CONTACT,RepCode_inst::REP_ORG_NAME,RepCode_Spec::REP_ORG_CONTACT,RepCode_Spec::REP_ORG_NAME,SlsCode::code_name
0,71.0,104454M1,17.0,NaN,CONROE,US,NORTH AMERICAN TRADE CORPORATION NORAMCO,TX,77304,1.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,Mike Guenther
1,80.0,104937,17.0,NaN,NEW CANEY,US,"PUMP SOLUTIONS, INC",TX,77357,3.0,...,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,Amy Oesau
2,80.0,104937M1,17.0,NaN,HOUSTON,NaN,PARK USA,TX,77040,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,Amy Oesau
3,80.0,104944,17.0,NaN,Euless,NaN,"Pump Solutions, Inc\n\n",TX,76040,2.0,...,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,Amy Oesau
4,80.0,103333D3,17.0,NaN,DALLAS,US,"ACCURATE TOOL GROUP,INC",TX,75228,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Amy Oesau
5,82.0,104974,17.0,NaN,ANGLETON,US,DELTA RIGGING & TOOLS INC,TX,77515,25.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
6,80.0,99294D1,17.0,NaN,CORPUS CHRISTI,US,KENNEDY WIRE ROPE & SLING COMPANY,TX,78405-4205,6.0,...,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,Amy Oesau
7,80.0,99236D1,17.0,NaN,SCHERTZ,US,XYLEM INC,TX,78154,NaN,...,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,Amy Oesau
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN
12,80.0,99236M3,17.0,NaN,SCHERTZ,US,XYLEM INC,TX,78154,NaN,...,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,Amy Oesau
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN
17,80.0,99236M4,17.0,NaN,Irving,NaN,Proserv Anchor Crane Group,Tx,75061,4.0,...,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,Amy Oesau
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN
22,80.0,99294D2,17.0,NaN,CORPUS CHRISTI,US,KENNEDY WIRE ROPE & SLING COMPANY,TX,78405-4205,6.0,...,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,Amy Oesau
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN

## Creating a New Data Frame with the selected Columns and Transforming the Names of Columns

In [3]:
#  populating a new df with the columns we need from the original data base - texas-df
clean_df_tx = texas_df[['bid_no_calc','BID_YEAR',\
                        'C_city','C_country',\
                        'C_cust_name',\
                        'C_state',\
                        'C_state',\
                        'C_zip',\
                        'contact_true_email',\
                        'contact_true_first',\
                        'Customer_ID',\
                        'intNotes',\
                        'IX_CUST_ID_SEQ',\
                        'Market',\
                        'PROJECT NAME',\
                        'Total_prop_v',\
                        'user_est_total',\
                        'valid']]
clean_df_tx

,bid_no_calc,BID_YEAR,C_city,C_country,C_cust_name,C_state,C_state,C_zip,contact_true_email,contact_true_first,Customer_ID,intNotes,IX_CUST_ID_SEQ,Market,PROJECT NAME,Total_prop_v,user_est_total,valid
0,104454M1,17.0,CONROE,US,NORTH AMERICAN TRADE CORPORATION NORAMCO,TX,TX,77304,georgeh@noramcousa.com,GEORGE,17403,rfq by phone. 10% discount direct per chris. ...,17403|1,Portable Structures,PORTABLE STRUCTURE WINCHES,30600.0,30600.0,Valid
1,104937,17.0,NEW CANEY,US,"PUMP SOLUTIONS, INC",TX,TX,77357,kenneth@pumpsolutions.net,KENNETH,20925,NaN,20925|3,Water/Wastewater,Montgomery Independant School District Lift St...,1633.1,0.0,Duplicate
2,104937M1,17.0,HOUSTON,NaN,PARK USA,TX,TX,77040,RBAKER@PARKUSA.COM,ROBIN,CP38101,NaN,CP38101|,Water/Wastewater,Montgomery Independant School District Lift St...,2333.0,2333.0,Valid
3,104944,17.0,Euless,NaN,"Pump Solutions, Inc\n\n",TX,TX,76040,BRETT@PUMPSOLUTIONS.NET,BRETT,CP37706,NaN,CP37706|2,Water/Wastewater,Rusk County - Youth Expo Center Sewer Improvem...,3115.7,3115.7,Valid
4,103333D3,17.0,DALLAS,US,"ACCURATE TOOL GROUP,INC",TX,TX,75228,ldoty@accuratetoolgroup.com,LANCE,20735,NaN,20735|1,Water/Wastewater,Sulphur Springs WWTP Improvements,23279.7,16911.8,Valid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3162,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3163,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3166,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Renaming the df with columns name that make more sense  - new data frame name
rename_df = clean_df_tx.rename(columns={'bid_no_calc':' Proposal #',\
                      'BID_YEAR':'Year',\
                      'C_city':'City',\
                      'C_cust_name':'Customer Name',\
                      'C_state':'State',\
                      'C_zip':'Zip Code',\
                      'contact_true_email':'Email',\
                      'contact_true_first':'Contact Firt Name',\
                      'Customer_ID':'Customer ID',\
                      'intNotes':'Notes',\
                      'Market':'Market',\
                      'PROJECT NAME':'Project Name',\
                      'Total_prop_v':'Proposal Value',\
                      'user_est_total':'Estimated Value',\
                      'valid':'Status'})


rename_df

,Proposal #,Year,City,C_country,Customer Name,State,State,Zip Code,Email,Contact Firt Name,Customer ID,Notes,IX_CUST_ID_SEQ,Market,Project Name,Proposal Value,Estimated Value,Status
0,104454M1,17.0,CONROE,US,NORTH AMERICAN TRADE CORPORATION NORAMCO,TX,TX,77304,georgeh@noramcousa.com,GEORGE,17403,rfq by phone. 10% discount direct per chris. ...,17403|1,Portable Structures,PORTABLE STRUCTURE WINCHES,30600.0,30600.0,Valid
1,104937,17.0,NEW CANEY,US,"PUMP SOLUTIONS, INC",TX,TX,77357,kenneth@pumpsolutions.net,KENNETH,20925,NaN,20925|3,Water/Wastewater,Montgomery Independant School District Lift St...,1633.1,0.0,Duplicate
2,104937M1,17.0,HOUSTON,NaN,PARK USA,TX,TX,77040,RBAKER@PARKUSA.COM,ROBIN,CP38101,NaN,CP38101|,Water/Wastewater,Montgomery Independant School District Lift St...,2333.0,2333.0,Valid
3,104944,17.0,Euless,NaN,"Pump Solutions, Inc\n\n",TX,TX,76040,BRETT@PUMPSOLUTIONS.NET,BRETT,CP37706,NaN,CP37706|2,Water/Wastewater,Rusk County - Youth Expo Center Sewer Improvem...,3115.7,3115.7,Valid
4,103333D3,17.0,DALLAS,US,"ACCURATE TOOL GROUP,INC",TX,TX,75228,ldoty@accuratetoolgroup.com,LANCE,20735,NaN,20735|1,Water/Wastewater,Sulphur Springs WWTP Improvements,23279.7,16911.8,Valid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3162,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3163,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3166,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Organizing the df by sorting the columns with better logic and importances 
organized_df= rename_df[[' Proposal #','Market','Project Name','Customer ID','Customer Name','Proposal Value','Estimated Value','Status','Notes','City','Zip Code','Contact Firt Name','Email','Year']]
organized_df

,Proposal #,Market,Project Name,Customer ID,Customer Name,Proposal Value,Estimated Value,Status,Notes,City,Zip Code,Contact Firt Name,Email,Year
0,104454M1,Portable Structures,PORTABLE STRUCTURE WINCHES,17403,NORTH AMERICAN TRADE CORPORATION NORAMCO,30600.0,30600.0,Valid,rfq by phone. 10% discount direct per chris. ...,CONROE,77304,GEORGE,georgeh@noramcousa.com,17.0
1,104937,Water/Wastewater,Montgomery Independant School District Lift St...,20925,"PUMP SOLUTIONS, INC",1633.1,0.0,Duplicate,NaN,NEW CANEY,77357,KENNETH,kenneth@pumpsolutions.net,17.0
2,104937M1,Water/Wastewater,Montgomery Independant School District Lift St...,CP38101,PARK USA,2333.0,2333.0,Valid,NaN,HOUSTON,77040,ROBIN,RBAKER@PARKUSA.COM,17.0
3,104944,Water/Wastewater,Rusk County - Youth Expo Center Sewer Improvem...,CP37706,"Pump Solutions, Inc\n\n",3115.7,3115.7,Valid,NaN,Euless,76040,BRETT,BRETT@PUMPSOLUTIONS.NET,17.0
4,103333D3,Water/Wastewater,Sulphur Springs WWTP Improvements,20735,"ACCURATE TOOL GROUP,INC",23279.7,16911.8,Valid,NaN,DALLAS,75228,LANCE,ldoty@accuratetoolgroup.com,17.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3162,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3163,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3166,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Eliminating the Water Waste Water Market and dropping the duplicates Proposals

In [6]:
# setting up a column "market" as index 
indexNames = organized_df[ organized_df['Market'] == "Water/Wastewater"].index

print(indexNames)

Int64Index([   1,    2,    3,    4,    6,    7,   12,   17,   22,  115,
            ...
            2738, 2746, 2751, 2837, 2918, 2981, 2986, 3001, 3034, 3083],
           dtype='int64', length=129)

In [7]:
# Delete water waste water rows withing the data frame 
organized_df.drop(indexNames , inplace=True)

organized_df

C:\Users\minor\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py:4102: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

,Proposal #,Market,Project Name,Customer ID,Customer Name,Proposal Value,Estimated Value,Status,Notes,City,Zip Code,Contact Firt Name,Email,Year
0,104454M1,Portable Structures,PORTABLE STRUCTURE WINCHES,17403,NORTH AMERICAN TRADE CORPORATION NORAMCO,30600.0,30600.0,Valid,rfq by phone. 10% discount direct per chris. ...,CONROE,77304,GEORGE,georgeh@noramcousa.com,17.0
5,104974,Oil & Gas,REQUEST FORWARDED FROM JIM,10084,DELTA RIGGING & TOOLS INC,27111.0,7417.0,Valid,NaN,ANGLETON,77515,PAULA,NaN,17.0
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3162,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3163,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3166,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# Drop Duplicates in Estimated Value
indexDuplicates = organized_df[ organized_df['Status'] == "Duplicate"].index
print(indexDuplicates)

Int64Index([  40,  110,  145,  281,  300,  371,  794,  929, 1077, 1119, 1316,
            1477, 1524, 1648, 1768, 1799, 2144, 2551, 2613, 2647, 2656, 2890,
            2932, 3040, 3045, 3094, 3109, 3119, 3134],
           dtype='int64')

In [9]:
organized_df.drop(indexDuplicates , inplace=True)
organized_df

,Proposal #,Market,Project Name,Customer ID,Customer Name,Proposal Value,Estimated Value,Status,Notes,City,Zip Code,Contact Firt Name,Email,Year
0,104454M1,Portable Structures,PORTABLE STRUCTURE WINCHES,17403,NORTH AMERICAN TRADE CORPORATION NORAMCO,30600.0,30600.0,Valid,rfq by phone. 10% discount direct per chris. ...,CONROE,77304,GEORGE,georgeh@noramcousa.com,17.0
5,104974,Oil & Gas,REQUEST FORWARDED FROM JIM,10084,DELTA RIGGING & TOOLS INC,27111.0,7417.0,Valid,NaN,ANGLETON,77515,PAULA,NaN,17.0
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3162,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3163,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3166,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Eliminating the NA withing the DF

In [10]:
# Drop Na values 
organized_df.dropna(axis=0,how='all',thresh=None, inplace =True)
organized_df

C:\Users\minor\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Proposal #,Market,Project Name,Customer ID,Customer Name,Proposal Value,Estimated Value,Status,Notes,City,Zip Code,Contact Firt Name,Email,Year
0,104454M1,Portable Structures,PORTABLE STRUCTURE WINCHES,17403,NORTH AMERICAN TRADE CORPORATION NORAMCO,30600.00,30600.00,Valid,rfq by phone. 10% discount direct per chris. ...,CONROE,77304,GEORGE,georgeh@noramcousa.com,17.0
5,104974,Oil & Gas,REQUEST FORWARDED FROM JIM,10084,DELTA RIGGING & TOOLS INC,27111.00,7417.00,Valid,NaN,ANGLETON,77515,PAULA,NaN,17.0
32,104722D1,Marine,Electrical cable payout/in for Research Barge,19151\n,TEXAS UNIVERSITY OF,31281.58,0.00,Valid,NaN,AUSTIN,78758,PURCHASING,NaN,17.0
45,105055,Bulk Handling,Trash Compactor,11269,BISHOP LIFTING PRODUCTS INC,14632.55,0.00,Valid,NaN,HOUSTON,77029,GAWAIN,gawain.seymour@lifting.com,17.0
51,105066,Aerospace,SpaceX Booster Rocket lift- Hydraulic Winch,10293,DELTA RIGGING & TOOLS INC,41478.51,41478.51,Valid,wes D,HURST,76053-7403,LARRY,loster@deltarigging.com,17.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3099,110321,Mining,IR Fulcrum Alternative,10966,INDUSTRIAL AIR TOOL 101,7130.50,868.00,Valid,NaN,PASADENA,77506,Alex,alex.hill@industrialairtool.com,17.0
3104,110357,Construction,Utlity Construction - Double drum waterfall,10084,DELTA RIGGING & TOOLS INC,13433.00,13433.00,Valid,NaN,ANGLETON,77515,Mark,matnip@deltarigging.com,17.0
3114,110318D1,Bulk Handling,IR Carpuller alternative,10966,INDUSTRIAL AIR TOOL 101,10560.00,10560.00,Valid,NaN,PASADENA,77506,Steve,shand@industrialairtool.com,17.0
3149,106737D2,Mining,,18992,SABINE MINING COMPANY SMC,24603.34,0.00,Valid,NaN,HALLSVILLE,75650-7413,Darren,NaN,17.0
3154,109210D1,Oil & Gas,IR Equivalent Discovery,18711,FORWARD PASS SUPPLY,740682.70,576440.00,New,NaN,THE WOODLANDS,77385,Greg,Greg.Korman@4wardpass.com,17.0

## Resetting the Index know the total amount of Data

In [11]:
# Reset Index 
organized_df.reset_index(drop=True, inplace=True)
organized_df

,Proposal #,Market,Project Name,Customer ID,Customer Name,Proposal Value,Estimated Value,Status,Notes,City,Zip Code,Contact Firt Name,Email,Year
0,104454M1,Portable Structures,PORTABLE STRUCTURE WINCHES,17403,NORTH AMERICAN TRADE CORPORATION NORAMCO,30600.00,30600.00,Valid,rfq by phone. 10% discount direct per chris. ...,CONROE,77304,GEORGE,georgeh@noramcousa.com,17.0
1,104974,Oil & Gas,REQUEST FORWARDED FROM JIM,10084,DELTA RIGGING & TOOLS INC,27111.00,7417.00,Valid,NaN,ANGLETON,77515,PAULA,NaN,17.0
2,104722D1,Marine,Electrical cable payout/in for Research Barge,19151\n,TEXAS UNIVERSITY OF,31281.58,0.00,Valid,NaN,AUSTIN,78758,PURCHASING,NaN,17.0
3,105055,Bulk Handling,Trash Compactor,11269,BISHOP LIFTING PRODUCTS INC,14632.55,0.00,Valid,NaN,HOUSTON,77029,GAWAIN,gawain.seymour@lifting.com,17.0
4,105066,Aerospace,SpaceX Booster Rocket lift- Hydraulic Winch,10293,DELTA RIGGING & TOOLS INC,41478.51,41478.51,Valid,wes D,HURST,76053-7403,LARRY,loster@deltarigging.com,17.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,110321,Mining,IR Fulcrum Alternative,10966,INDUSTRIAL AIR TOOL 101,7130.50,868.00,Valid,NaN,PASADENA,77506,Alex,alex.hill@industrialairtool.com,17.0
235,110357,Construction,Utlity Construction - Double drum waterfall,10084,DELTA RIGGING & TOOLS INC,13433.00,13433.00,Valid,NaN,ANGLETON,77515,Mark,matnip@deltarigging.com,17.0
236,110318D1,Bulk Handling,IR Carpuller alternative,10966,INDUSTRIAL AIR TOOL 101,10560.00,10560.00,Valid,NaN,PASADENA,77506,Steve,shand@industrialairtool.com,17.0
237,106737D2,Mining,,18992,SABINE MINING COMPANY SMC,24603.34,0.00,Valid,NaN,HALLSVILLE,75650-7413,Darren,NaN,17.0
238,109210D1,Oil & Gas,IR Equivalent Discovery,18711,FORWARD PASS SUPPLY,740682.70,576440.00,New,NaN,THE WOODLANDS,77385,Greg,Greg.Korman@4wardpass.com,17.0

## Exporting the Clean and Organized Data Frame

In [15]:
# export the data frame to csv fole

organized_df.to_csv("Output_files/texas_df_2017.csv",index=False)